/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var attributes = {
    "feedURL": "http://localhost/apple/Feeds/TodayConcertsListGD.php?day=&month=",
    "maxAgeToShow": "-1",
    "numItemsToShow": "-1",
    "topStories": "10"
};


// this is the URL that gets loaded when the button in the upper right corner is pressed when the image is the Internet Archive Logo
// this is referenced in main.js load


var theArchivenewurl = 'http://localhost/apple/Feeds/TodayConcertsListAllBands.php?day=&month=';


// this is the URL that gets loaded when the button in the upper right corner is pressed when the image is a SYF
// this is referenced in main.js load

var theDeadnewurl = 'http://localhost/apple/Feeds/TodayConcertsListGD.php?day=&month=';

// this is the base URL that gets loaded when a show is clicked on - it is referenced in the main.js detailController

var newSongListBaseurl = 'http://localhost/apple/Feeds/ConcertDetailsRSS.php?';
